# patrol_params.yaml
patrol_navigator_node:
  ros__parameters:
    # ==========================================
    # 1. 导航与避障策略参数
    # ==========================================
    obstacle_radius: 5.0      # 障碍物避让半径 (米)
    stall_timeout: 20.0       # 原地打转超时时间 (秒)
    stall_distance: 0.2       # 判定卡死的最小移动距离 (米)

    # ==========================================
    # 2. 巡逻航点配置 (JSON 字符串格式)
    # type: "task" 表示任务点（硬闯不避让违停、不判断卡死超时、到达后执行任务）
    # type: "via"  表示途径点（主动避让违停、检测原地打转卡死、到达后不停留）
    # ==========================================
    
    # 当前生效：室外示例 3
    waypoints_json: >
      [
        {"x": 5.7, "y": -69.6, "type": "via"},
        {"x": 105.7, "y": -81.0, "type": "via"},
        {"x": 106.0, "y": -64.0, "type": "via"},
        {"x": -70.64, "y": -45.30, "type": "via"},
        {"x": -84.76, "y": -60.08, "type": "via"},
        {"x": 5.7, "y": -69.6, "type": "via"},
        {"x": 5.20, "y": -53.20, "type": "via"}
      ]

    # =========================================================
    # [备用航点区] 如果需要使用其他路线，只需将上面的 waypoints_json 注释掉，
    # 并将下面某个配置的注释取消即可。
    # =========================================================

    # 【备用】室内场景坐标点
    # waypoints_json: >
    #   [
    #     {"x": -1.4, "y": 5.0, "type": "via"},
    #     {"x": -13.1, "y": 6.3, "type": "via"},
    #     {"x": -13.5, "y": 1.35, "type": "task"},
    #     {"x": -1.6, "y": 0.0, "type": "task"}
    #   ]

    # 【备用】室外示例 1
    # waypoints_json: >
    #   [
    #     {"x": 5.7, "y": -68.6, "type": "via"},
    #     {"x": 105.7, "y": -79.0, "type": "via"},
    #     {"x": 104.5, "y": -91.2, "type": "task"},
    #     {"x": 5.7, "y": -79.2, "type": "task"}
    #   ]

    # 【备用】室外示例 2
    # waypoints_json: >
    #   [
    #     {"x": 5.7, "y": -68.6, "type": "via"},
    #     {"x": 105.7, "y": -79.0, "type": "via"},
    #     {"x": 103.5, "y": -91.2, "type": "task"},
    #     {"x": 106.0, "y": -64.0, "type": "task"},
    #     {"x": 5.0, "y": -53.0, "type": "via"}
    #   ]